version: "3"
services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3030:3000
    volumes:
      - ./inter_admin_front:/react-app
    tty: true
    command: sh -c "npm start"